CREATE TABLE bookery_bookshelf (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER REFERENCES users(id),
  book_id INTEGER REFERENCES books(id),
  review TEXT,
  rating INTEGER
)